///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ButtonTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ResizeBrowser recording.
    /// </summary>
    [TestModule("3df79e3f-03d8-4bde-9f63-a83ff8db2b3b", ModuleType.Recording, 1)]
    public partial class ResizeBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ButtonTestRepository repository.
        /// </summary>
        public static ButtonTestRepository repo = ButtonTestRepository.Instance;

        static ResizeBrowser instance = new ResizeBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ResizeBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ResizeBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Shrinking SIze
            Report.Log(ReportLevel.Info, "Section", "Shrinking SIze", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'IEBRowser' at 6;5.", repo.IEBRowser.SelfInfo, new RecordItemIndex(1));
            repo.IEBRowser.Self.MoveTo("6;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'IEBRowser' at 430;293.", repo.IEBRowser.SelfInfo, new RecordItemIndex(2));
            repo.IEBRowser.Self.MoveTo("430;293");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            //Delay.Duration(1000, false);
            
            // Original Size
            Report.Log(ReportLevel.Info, "Section", "Original Size", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'IEBRowser' at 6;5.", repo.IEBRowser.SelfInfo, new RecordItemIndex(5));
            repo.IEBRowser.Self.MoveTo("6;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'IEBRowser' at -430;-293.", repo.IEBRowser.SelfInfo, new RecordItemIndex(6));
            repo.IEBRowser.Self.MoveTo("-430;-293");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            // Reset Mouse
            Report.Log(ReportLevel.Info, "Section", "Reset Mouse", new RecordItemIndex(7));
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            //Delay.Duration(1000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IEBRowser' at 1;1.", repo.IEBRowser.SelfInfo, new RecordItemIndex(9));
            //repo.IEBRowser.Self.Click("1;1");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.Calculator' at 24;21.", repo.Explorer.CalculatorInfo, new RecordItemIndex(10));
            repo.Explorer.Calculator.Click("24;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Close' at 20;21.", repo.Calculator.CloseInfo, new RecordItemIndex(11));
            repo.Calculator.Close.Click("20;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexSite.TraceLogCreation' at 66;17.", repo.RanorexSite.TraceLogCreationInfo, new RecordItemIndex(12));
            repo.RanorexSite.TraceLogCreation.Click("66;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexSite.SubMenu.Introduction' at 121;29.", repo.RanorexSite.SubMenu.IntroductionInfo, new RecordItemIndex(13));
            repo.RanorexSite.SubMenu.Introduction.Click("121;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexSite.SubMenu.LeverageTheData' at 124;18.", repo.RanorexSite.SubMenu.LeverageTheDataInfo, new RecordItemIndex(14));
            repo.RanorexSite.SubMenu.LeverageTheData.Click("124;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexSite.SubMenu.TraceLogs' at 115;19.", repo.RanorexSite.SubMenu.TraceLogsInfo, new RecordItemIndex(15));
            repo.RanorexSite.SubMenu.TraceLogs.Click("115;19");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
